name: dfm-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pythonocc-core=7.8.1.1
  - pip
  - pip:
    - pymeshlab>=2021.10
    - numpy>=1.20.0
    - scipy>=1.7.0
    - fastapi>=0.95.0
    - uvicorn>=0.22.0
    - python-multipart>=0.0.6
    - requests>=2.28.0
    - trimesh>=3.20.0
    - pydantic>=1.10.0
    - open3d>=0.16.0
    # Payment processing
    - stripe>=5.0.0
    # Slack integration
    - slack_sdk>=3.19.0
    # Environment variables
    - python-dotenv>=1.0.0
    # File handling
    - aiofiles>=23.1.0